name: 'push-package-version-tag-action'
description: 'create and push package.json tag'

inputs:
  github-token:
    description: 'github token with access to merge in head-branch'
    required: true

  prefix:
    description: 'tag prefix'
    required: true
    default: ''

runs:
  using: 'node12'
  main: 'index.js'
